apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: permanent-earwig-python 
  janus-idp.io/tekton: permanent-earwig-python
  backstage.io/kubernetes-id: permanent-earwig-python
  backstage.io/kubernetes-namespace: flavius-e2e 
  app.kubernetes.io/part-of: permanent-earwig-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  